openapi: 3.0.0
info:
  version: v4 - Hunt Valley
  description: RESTful API for the drchrono EHR platform providing access to patient records, clinical encounters, appointments, prescriptions, billing, lab orders, and practice administration with OAuth 2.0 authentication and HIPAA-compliant data exchange.
  x-logo:
    url: https://www.drchrono.com/site_media/images/logos/drchrono-black-wpadding.png
    altText: DrChrono Logo
  title: DrChrono EHR REST Administrative Billing API
servers:
- url: https://app.drchrono.com
tags:
- description: Create and manage billing resources
  name: Billing
paths:
  /api/day_sheet_charges:
    get:
      description: Retrieve daysheet charges report for a given date range
      tags:
      - Billing
      x-permissions:
      - billing
      - access-patient-payments
      security:
      - drchrono_oauth2:
        - billing
      operationId: daysheet_charges_list
  /api/eligibility_checks:
    get:
      tags:
      - Billing
      x-permissions:
      - scheduling
      - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - calendar:read
        - calendar:write
        - patients:read
        - patients:write
      operationId: eligibility_checks_list
      description: Retrieve or search past eligibility checks for patient
  /api/patient_authorizations:
    get:
      tags:
      - Billing
      x-permissions: null
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security: null
      operationId: patient_authorizations_list
      description: Retrieve or search patient authorizations
  /api/custom_insurance_plan_names/{id}:
    get:
      tags:
      - Billing
      x-permissions:
      - settings
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - settings:read
        - settings:write
      operationId: custom_insurance_plan_names_read
      description: Retrieve an existing custom insurance plan name
  /api/line_items_list:
    post:
      tags:
      - Billing
      x-permissions:
      - billing
      - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - billing:read
      operationId: line_items_list_create
      description: Create a billing line items list request
    get:
      tags:
      - Billing
      x-permissions:
      - billing
      - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - billing:read
      operationId: line_items_list_list
      description: Retrieve the list of billing line items
  /api/day_sheet_patient_payments:
    get:
      description: Retrieve daysheet cash report for a given date range
      tags:
      - Billing
      x-permissions:
      - billing
      - access-patient-payments
      security:
      - drchrono_oauth2:
        - billing
      operationId: day_sheet_patient_payments_list
  /api/eligibility_checks/{id}:
    get:
      tags:
      - Billing
      x-permissions:
      - scheduling
      - manage-patients
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - calendar:read
        - calendar:write
        - patients:read
        - patients:write
      operationId: eligibility_checks_read
      description: Retrieve an existing past eligibility check
  /api/comm_logs:
    post:
      tags:
      - Billing
      x-permissions:
      - scheduling
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - calendar:read
        - calendar:write
      operationId: comm_logs_create
      description: Create communication (phone call) logs
    get:
      tags:
      - Billing
      x-permissions:
      - scheduling
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - calendar:read
        - calendar:write
      operationId: comm_logs_list
      description: Retrieve or search communicatioin (phone call) logs
  /api/day_sheet_credits:
    get:
      description: Retrieve daysheet credits/adjustments report for a given date range
      tags:
      - Billing
      x-permissions:
      - billing
      - access-patient-payments
      security:
      - drchrono_oauth2:
        - billing
      operationId: daysheet_credits_list
  /api/transactions_list:
    post:
      tags:
      - Billing
      x-permissions:
      - billing
      - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - billing:read
        - billing:write
      operationId: transactions_list_create
      description: 'Create transactions list request.  Use the UUID returned in the response to retrieve the batch of records. Results returned in order of id or updated_at.

        '
    get:
      tags:
      - Billing
      x-permissions:
      - billing
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - billing:read
        - billing:write
      operationId: transactions_list_list
      description: Retrieve or search transactions in batches. Results returned in order of ID or updated_at.
  /api/patient_payments/{id}:
    get:
      tags:
      - Billing
      x-permissions:
      - access-patient-payments
      - billing
      - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - billing:patient-payment:read
        - billing:patient-payment:write
      operationId: patient_payments_read
      description: Retrieve an existing patient payment
  /api/patient_payments:
    post:
      tags:
      - Billing
      x-permissions:
      - access-patient-payments
      - billing
      - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - billing:patient-payment:read
        - billing:patient-payment:write
      operationId: patient_payments_create
      description: Create patient payment
    get:
      tags:
      - Billing
      x-permissions:
      - access-patient-payments
      - billing
      - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - billing:patient-payment:read
        - billing:patient-payment:write
      operationId: patient_payments_list
      description: Retrieve or search patient payments
  /api/clinical_note_field_values_list:
    post:
      tags:
      - Billing
      x-permissions:
      - scheduling
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - calendar:read
        - patients:read
      operationId: clinical_note_field_values_list_create
      description: 'Create clinical note field value list request.  Use the UUID returned in the response to retrieve the batch of records. Results returned in order of ID.

        '
  /api/billing_profiles:
    get:
      tags:
      - Billing
      x-permissions:
      - billing
      - show-billing-tab
      x-practice-access: '"share_billing_profiles" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - billing:read
        - billing:write
      operationId: billing_profiles_list
      description: Retrieve or search billing profiles
  /api/billing_profiles/{id}:
    get:
      tags:
      - Billing
      x-permissions:
      - billing
      - show-billing-tab
      x-practice-access: '"share_billing_profiles" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - billing:read
        - billing:write
      operationId: billing_profiles_read
      description: Retrieve an existing billing profiles
  /api/line_item_deletions:
    get:
      tags:
      - Billing
      x-permissions:
      - billing
      - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - billing:read
      operationId: line_item_deletions_list
      description: 'Retrieve or search billing line item deletions. When a billing line item is deleted, a record of its original ID and the appointment it was attached to will be logged and is accessible from this resource.

        '
  /api/transactions:
    get:
      tags:
      - Billing
      x-permissions:
      - billing
      - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - billing:read
        - billing:write
      operationId: transactions_list
      description: Retrieve or search insurance transactions associated with billing line items
  /api/custom_insurance_plan_names:
    get:
      tags:
      - Billing
      x-permissions:
      - settings
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - settings:read
        - settings:write
      operationId: custom_insurance_plan_names_list
      description: Retrieve or search custom insurance plan names
  /api/day_sheet_totals:
    get:
      description: Retrieve daysheet totals report for a given date range
      tags:
      - Billing
      x-permissions:
      - billing
      - access-patient-payments
      security:
      - drchrono_oauth2:
        - billing
      operationId: daysheet_totals_list
  /api/transactions/{id}:
    get:
      tags:
      - Billing
      x-permissions:
      - billing
      - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - billing:read
        - billing:write
      operationId: transactions_read
      description: Retrieve an existing insurance transaction
  /api/procedures:
    get:
      tags:
      - Billing
      x-permissions:
      - billing
      - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - billing:read
        - billing:write
      operationId: procedures_list
  /api/eligibility_checks_list:
    get:
      tags:
      - Billing
      x-permissions:
      - scheduling
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - calendar:read
        - patients:read
      operationId: eligibility_checks_list_list
      description: Retrieve or search eligibility checks in batches. Results returned in order of ID or updated_at.
  /api/procedures/{id}:
    get:
      tags:
      - Billing
      x-permissions:
      - billing
      - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - billing:read
        - billing:write
      operationId: procedures_read
  /api/line_items/{id}:
    put:
      tags:
      - Billing
      x-permissions:
      - billing
      - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - billing:read
        - billing:write
      operationId: line_items_update
    patch:
      tags:
      - Billing
      x-permissions:
      - billing
      - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - billing:read
        - billing:write
      operationId: line_items_partial_update
    get:
      tags:
      - Billing
      x-permissions:
      - billing
      - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - billing:read
        - billing:write
      operationId: line_items_read
      description: Retrieve an existing billing line item
    delete:
      tags:
      - Billing
      x-permissions:
      - billing
      - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - billing:read
        - billing:write
      operationId: line_items_delete
  /api/patient_payment_log:
    get:
      tags:
      - Billing
      x-permissions:
      - billing
      - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - billing:read
        - billing:write
      operationId: patient_payment_log_list
      description: Retrieve or search patient payment logs
  /api/patient_payment_log/{id}:
    get:
      tags:
      - Billing
      x-permissions:
      - billing
      - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - billing:read
        - billing:write
      operationId: patient_payment_log_read
      description: Retrieve an existing patient payment log
  /api/comm_logs/{id}:
    put:
      tags:
      - Billing
      x-permissions:
      - scheduling
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - calendar:read
        - calendar:write
      operationId: comm_logs_update
      description: Update an existing communication (phone call) logs
    patch:
      tags:
      - Billing
      x-permissions:
      - scheduling
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - calendar:read
        - calendar:write
      operationId: comm_logs_partial_update
      description: Update an existing communication (phone call) logs
    get:
      tags:
      - Billing
      x-permissions:
      - scheduling
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - calendar:read
        - calendar:write
      operationId: comm_logs_read
      description: Retrieve an existing communication (phone call) logs
  /api/line_items:
    post:
      tags:
      - Billing
      x-permissions:
      - billing
      - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - billing:read
        - billing:write
      operationId: line_items_create
      description: Create billing line item for appointments
    get:
      tags:
      - Billing
      x-permissions:
      - billing
      - show-billing-tab
      x-practice-access: '"share_patients" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - billing:read
        - billing:write
      operationId: line_items_list
      description: Retrieve or search billing line items
components:
  securitySchemes:
    drchrono_oauth2:
      type: oauth2
      description: ''
      flows:
        authorizationCode:
          scopes:
            billing:patient-payment:read: View patient payment information
            billing:read: View billing information.
            patients:read: View detailed patient information.
            user:write: Edit select account information, such as creating new exam rooms.
            messages:write: Create and modify messages in your message center.
            messages:read: View messages in your message center.
            tasks:write: Create and modify tasks in your tasks center
            tasks:read: View tasks in your tasks center
            labs:write: Create and modify patient lab orders and results.
            patients:write: Create patients and modify detailed patient information.
            settings:write: Create resources that requires Settings permission, such as custom fields.
            billing:patient-payment:write: Modify patient payment information
            clinical:write: Create and modify clinical information, such as vitals, clinical notes, medications and diagnoses.
            patients:summary:write: Create new patients and set their name, chart_id, age, and gender.
            calendar:read: View your appointments.
            user:read: View your basic information.
            billing:write: Modify billing information.
            settings:read: View resources that requires Settings permission, such as custom fields.
            labs:read: View patient lab orders and results.
            calendar:write: Schedule appointments and modify the data associated with them.
            patients:summary:read: View summary information about your patients. This includes patients' name, chart_id, age, and gender.
            clinical:read: View clinical information, such as vitals, clinical notes, medications and diagnoses.
          tokenUrl: https://app.drchrono.com/o/token/
          authorizationUrl: https://app.drchrono.com/o/authorize/
