openapi: 3.0.0
info:
  version: v4 - Hunt Valley
  description: RESTful API for the drchrono EHR platform providing access to patient records, clinical encounters, appointments, prescriptions, billing, lab orders, and practice administration with OAuth 2.0 authentication and HIPAA-compliant data exchange.
  x-logo:
    url: https://www.drchrono.com/site_media/images/logos/drchrono-black-wpadding.png
    altText: DrChrono Logo
  title: DrChrono EHR REST Administrative Practice Management API
servers:
- url: https://app.drchrono.com
tags:
- description: Create and manage practice management resources
  name: Practice Management
paths:
  /api/doctor_work_schedule/{id}:
    put:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - user:read
        - user:write
      operationId: doctor_work_schedule_update
      description: Update an existing doctor's entire work schedule
    patch:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - user:read
        - user:write
      operationId: doctor_work_schedule_partial_update
      description: Update an existing doctor's work schedule
    get:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - user:read
        - user:write
      operationId: doctor_work_schedule_read
      description: Retrieve a work schedule for the doctor (beta)
  /api/messages:
    post:
      tags:
      - Practice Management
      x-permissions:
      - message-center
      x-practice-access: '"share_communications" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - messages:read
        - messages:write
      operationId: messages_create
      description: Create messages in doctor's message center
    get:
      tags:
      - Practice Management
      x-permissions:
      - message-center
      x-practice-access: '"share_communications" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - messages:read
        - messages:write
      operationId: messages_list
      description: Retrieve or search messages in doctor's message center
  /api/task_categories:
    post:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - tasks:read
        - tasks:write
      operationId: task_categories_create
      description: Create a task category
    get:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - tasks:read
        - tasks:write
      operationId: task_categories_list
      description: Retrieve or search task categories
  /api/offices/{id}/add_exam_room:
    post:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - user:read
        - user:write
      operationId: offices_add_exam_room
      description: Add an exam room to the office
  /api/inventory_vaccines/{id}:
    get:
      tags:
      - Practice Management
      x-permissions:
      - clinical-notes
      x-practice-access: '"share_inventory" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - clinical:read
        - clinical:write
      operationId: inventory_vaccines_read
      description: Retrieve an existing vaccine inventory
  /api/offices:
    get:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - user:read
        - user:write
      operationId: offices_list
      description: Retrieve or search offices
  /api/task_statuses/{id}:
    put:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - tasks:read
        - tasks:write
      operationId: task_statuses_update
      description: Update an existing task status
    patch:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - tasks:read
        - tasks:write
      operationId: task_statuses_partial_update
      description: Update an existing task status
    get:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - tasks:read
        - tasks:write
      operationId: task_statuses_read
      description: Retrieve an existing task status
  /api/office_work_schedule:
    get:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2: []
      operationId: office_work_schedule_list
      description: Get the work schedule for the authed doctor's primary office (beta)
  /api/task_templates:
    post:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - tasks:read
        - tasks:write
      operationId: task_templates_create
      description: Create a task template
    get:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - tasks:read
        - tasks:write
      operationId: task_templates_list
      description: Retrieve or search task templates
  /api/office_work_schedule/{id}:
    put:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - user:read
        - user:write
      operationId: office_work_schedule_update
      description: Update an existing office's entire work schedule
    patch:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - user:read
        - user:write
      operationId: office_work_schedule_partial_update
      description: Update an existing office's work schedule
    get:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - user:read
        - user:write
      operationId: office_work_schedule_read
      description: Retrieve a work schedule (beta)
  /api/inventory_categories/{id}:
    get:
      tags:
      - Practice Management
      x-permissions:
      - clinical-notes
      x-practice-access: '"share_inventory" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - clinical:read
        - clinical:write
      operationId: inventory_categories_read
      description: Retrieve an existing inventory category
  /api/tasks/{id}:
    put:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - tasks:read
        - tasks:write
      operationId: tasks_update
      description: Update an existing task
    patch:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - tasks:read
        - tasks:write
      operationId: tasks_partial_update
      description: Update an existing task
    get:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - tasks:read
        - tasks:write
      operationId: tasks_read
      description: Retrieve an existing task
  /api/doctor_work_schedule:
    get:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2: []
      operationId: doctor_work_schedule_list
      description: Get the work schedule for the authed doctor's primary office (beta)
  /api/inventory_categories:
    get:
      tags:
      - Practice Management
      x-permissions:
      - clinical-notes
      x-practice-access: '"share_inventory" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - clinical:read
        - clinical:write
      operationId: inventory_categories_list
      description: Retrieve or search inventory categories
  /api/task_statuses:
    post:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - tasks:read
        - tasks:write
      operationId: task_statuses_create
      description: Create a task status
    get:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - tasks:read
        - tasks:write
      operationId: task_statuses_list
      description: Retrieve or search task statuses
  /api/task_templates/{id}:
    put:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - tasks:read
        - tasks:write
      operationId: task_templates_update
      description: Update an existing task template
    patch:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - tasks:read
        - tasks:write
      operationId: task_templates_partial_update
      description: Update an existing task template
    get:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - tasks:read
        - tasks:write
      operationId: task_templates_read
      description: Retrieve an existing task template
  /api/task_notes:
    post:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - tasks:read
        - tasks:write
      operationId: task_notes_create
      description: Create a task note
    get:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - tasks:read
        - tasks:write
      operationId: task_notes_list
      description: Retrieve or search task notes
  /api/tasks:
    post:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - tasks:read
        - tasks:write
      operationId: tasks_create
      description: Create a task
    get:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - tasks:read
        - tasks:write
      operationId: tasks_list
      description: Retrieve or search tasks
  /api/inventory_vaccines:
    post:
      tags:
      - Practice Management
      x-permissions:
      - clinical-notes
      x-practice-access: '"share_inventory" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - clinical:read
        - clinical:write
      operationId: inventory_vaccines_create
      description: Create vaccine inventory
    get:
      tags:
      - Practice Management
      x-permissions:
      - clinical-notes
      x-practice-access: '"share_inventory" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - clinical:read
        - clinical:write
      operationId: inventory_vaccines_list
      description: Retrieve or search vaccine inventories
  /api/task_categories/{id}:
    put:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - tasks:read
        - tasks:write
      operationId: task_categories_update
      description: Update an existing task category
    patch:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - tasks:read
        - tasks:write
      operationId: task_categories_partial_update
      description: Update an existing task category
    get:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - tasks:read
        - tasks:write
      operationId: task_categories_read
      description: Retrieve an existing task category
  /api/task_notes/{id}:
    put:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - tasks:read
        - tasks:write
      operationId: task_notes_update
      description: Update an existing task note
    patch:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - tasks:read
        - tasks:write
      operationId: task_notes_partial_update
      description: Update an existing task note
    get:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - tasks:read
        - tasks:write
      operationId: task_notes_read
      description: Retrieve an existing task note
  /api/messages/{id}:
    put:
      tags:
      - Practice Management
      x-permissions:
      - message-center
      x-practice-access: '"share_communications" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - messages:read
        - messages:write
      operationId: messages_update
      description: Update an existing message in doctor's message center
    patch:
      tags:
      - Practice Management
      x-permissions:
      - message-center
      x-practice-access: '"share_communications" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - messages:read
        - messages:write
      operationId: messages_partial_update
      description: Update an existing message in doctor's message center
    get:
      tags:
      - Practice Management
      x-permissions:
      - message-center
      x-practice-access: '"share_communications" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - messages:read
        - messages:write
      operationId: messages_read
      description: Retrieve an existing message in doctor's message center
    delete:
      tags:
      - Practice Management
      x-permissions:
      - message-center
      x-practice-access: '"share_communications" need to be set for data access among practice'
      security:
      - drchrono_oauth2:
        - messages:read
        - messages:write
      operationId: messages_delete
      description: Delete an existing message in doctor's message center
  /api/offices/{id}:
    put:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - user:read
        - user:write
      operationId: offices_update
      description: Update an existing office
    patch:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - user:read
        - user:write
      operationId: offices_partial_update
      description: Update an existing office
    get:
      tags:
      - Practice Management
      x-permissions: []
      x-practice-access: Data access among practice is available
      security:
      - drchrono_oauth2:
        - user:read
        - user:write
      operationId: offices_read
      description: Retrieve an existing office
components:
  securitySchemes:
    drchrono_oauth2:
      type: oauth2
      description: ''
      flows:
        authorizationCode:
          scopes:
            billing:patient-payment:read: View patient payment information
            billing:read: View billing information.
            patients:read: View detailed patient information.
            user:write: Edit select account information, such as creating new exam rooms.
            messages:write: Create and modify messages in your message center.
            messages:read: View messages in your message center.
            tasks:write: Create and modify tasks in your tasks center
            tasks:read: View tasks in your tasks center
            labs:write: Create and modify patient lab orders and results.
            patients:write: Create patients and modify detailed patient information.
            settings:write: Create resources that requires Settings permission, such as custom fields.
            billing:patient-payment:write: Modify patient payment information
            clinical:write: Create and modify clinical information, such as vitals, clinical notes, medications and diagnoses.
            patients:summary:write: Create new patients and set their name, chart_id, age, and gender.
            calendar:read: View your appointments.
            user:read: View your basic information.
            billing:write: Modify billing information.
            settings:read: View resources that requires Settings permission, such as custom fields.
            labs:read: View patient lab orders and results.
            calendar:write: Schedule appointments and modify the data associated with them.
            patients:summary:read: View summary information about your patients. This includes patients' name, chart_id, age, and gender.
            clinical:read: View clinical information, such as vitals, clinical notes, medications and diagnoses.
          tokenUrl: https://app.drchrono.com/o/token/
          authorizationUrl: https://app.drchrono.com/o/authorize/
